[package]
name = "meta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
token = { path = "../token" }
chumsky = "0.9.3"
codespan-reporting = "0.11.1"
