[package]
name = "zapc_token"
version = "0.1.0"
edition = "2021"
private = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zapc_meta = { path = "../zapc_meta" }
lasso = "0.7.2"
logos = "0.14.0"
