[package]
name = "zapc_ast"
version = "0.1.0"
edition = "2021"
private = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zapc_token = { path = "../zapc_token" }
zapc_meta = { path = "../zapc_meta" }
lasso = "0.7.2"
